### ISSUE TITLE
好不容易把依赖都安装成功了，但是运行main.py报错了

### ISSUE THREAD

**Issue by zhoudahong** [cuifengcn/wechat-video-generate#4]
Traceback (most recent call last):
  File "D:\PythonDevWorkSpace\wechat-video-generate-0.1\main.py", line 2, in <module>
    import flet as ft
  File "D:\Softwares\Develop\Python\lib\site-packages\flet\__init__.py", line 1, in <module>
    from flet import (
  File "D:\Softwares\Develop\Python\lib\site-packages\flet\audio.py", line 7, in <module>
    from beartype import beartype
  File "D:\Softwares\Develop\Python\lib\site-packages\beartype\__init__.py", line 57, in <module>
    from beartype._decor.decormain import beartype
  File "D:\Softwares\Develop\Python\lib\site-packages\beartype\_decor\decormain.py", line 24, in <module>
    from beartype._data.datatyping import (
  File "D:\Softwares\Develop\Python\lib\site-packages\beartype\_data\datatyping.py", line 129, in <module>
    BeartypeReturn = Union[BeartypeableT, BeartypeConfedDecorator]
  File "D:\Softwares\Develop\Python\lib\typing.py", line 243, in inner
    return func(*args, **kwds)
  File "D:\Softwares\Develop\Python\lib\typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "D:\Softwares\Develop\Python\lib\typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "D:\Softwares\Develop\Python\lib\typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'

**Comment by moshstudio** [comment]
更新下flet试试
